baseurl = "https://ethanou.com"
languageCode = "en-us"
title = "Ethan Ou"

# canonifyurls = "true"
paginate = 20
publishDir = "docs" # if you use GitHub to deploy
disqusShortname = "yourdisqusshortname"
googleAnalytics = "UA-123-45"

# pygmentsCodeFences = true
# pygmentsStyle="monokai"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[params]
    description = "Ethan Ou's personal website"
    images = [""]

[author]
    name = "Ethan Ou"

[social]
    twitter = ""
    facebook = ""
    facebook_admin = ""
    linkedin = ""
    instagram = ""
    googleplus = ""
    github = "ethan-ou"
    gitlab = ""
    pinterest = ""
    tumblr = ""
    vimeo = ""
    youtube = ""

# if you want markdown WYSIWYG line break
[blackfriday]
    extensions = ["hardLineBreak"]

# main menu
[[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 1
# [[menu.main]]
#     name = "Projects"
#     url = "/projects/"
#     weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[[params.footer]]
    name = "Articles"
    url = "/articles/"
    weight = 1
# [[params.footer]]
#     name = "Projects"
#     url = "/projects/"
#     weight = 2
[[params.footer]]
    name = "About"
    url = "/about/"
    weight = 3

# Add footer contents here
# [[params.footer]]
#     name = "Ethan Ou"
#     url = false
# [[params.footer]]
#     name = "Mail"
#     url = "mailto:"
