baseurl = "https://friendly-kilby-795b5d.netlify.com"
languageCode = "en-us"
title = "Ethan Ou"

canonifyurls = "true"
paginate = 20
publishDir = "docs" # if you use GitHub to deploy
disqusShortname = "yourdisqusshortname"
googleAnalytics = "UA-123-45"

pygmentsCodeFences = true
pygmentsStyle="monokai"

[params]
    description = "Ethan Ou's personal website"
    keywords = "mystery, history, medicine"
    images = [""]

[author]
    name = "Ethan Ou"

[social]
    twitter = ""
    facebook = ""
    facebook_admin = ""
    linkedin = ""
    instagram = ""
    googleplus = ""
    github = "ethan-ou"
    gitlab = ""
    pinterest = ""
    tumblr = ""
    vimeo = ""
    youtube = ""

# if you want markdown WYSIWYG line break
[blackfriday]
    extensions = ["hardLineBreak"]

# main menu
[[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 1
[[menu.main]]
    name = "Projects"
    url = "/projects-index/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

# Add footer contents here
# [[params.footer]]
#     name = "Ethan Ou"
#     url = false
# [[params.footer]]
#     name = "Mail"
#     url = "mailto:"
